# Generated by Django 5.1.6 on 2025-03-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_merchant', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='expenses.receipt')),
            ],
        ),
    ]
